-- ════════════════════════════════════════════════════════════════
-- 014 — Merchant settlement ledger
--
-- Records what the platform owes each merchant for orders it collected
-- money on (PayWay QR), the commission it keeps, and how/when merchants
-- are paid out. Works today with manual bank transfers; the same tables
-- carry ABA PayWay Split & Payout later (settlement_method = 'aba_split').
--
-- Requires 013_payway_payments.sql. Safe to re-run.
-- ════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. Merchant payout settings ─────────────────────────────────

ALTER TABLE merchants ADD COLUMN IF NOT EXISTS aba_account text;            -- added in 013
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS aba_account_name text;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS payout_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS payout_verification_status text NOT NULL DEFAULT 'unverified';
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS payout_verified_at timestamptz;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS payout_verified_by text;
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS payout_rejection_reason text;
-- Per-merchant commission override (percent). NULL = platform default.
ALTER TABLE merchants ADD COLUMN IF NOT EXISTS commission_rate numeric(5,2);

DO $$ BEGIN
  ALTER TABLE merchants ADD CONSTRAINT merchants_payout_verification_status_chk
    CHECK (payout_verification_status IN ('unverified', 'pending', 'verified', 'rejected'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE merchants ADD CONSTRAINT merchants_commission_rate_chk
    CHECK (commission_rate IS NULL OR (commission_rate >= 0 AND commission_rate <= 100));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 2. Order snapshots ──────────────────────────────────────────
-- Commission rate frozen at order time so a later rate change never
-- alters what was promised on an existing order.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS commission_rate numeric(5,2);
-- How the latest PayWay QR routes money: 'platform' (we collect) or
-- 'aba_split' (ABA pays the seller's share directly).
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payout_mode text NOT NULL DEFAULT 'platform';

DO $$ BEGIN
  ALTER TABLE orders ADD CONSTRAINT orders_payout_mode_chk
    CHECK (payout_mode IN ('platform', 'aba_split'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 3. Payouts (one transfer to one merchant) ───────────────────

CREATE TABLE IF NOT EXISTS merchant_payouts (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id        bigint NOT NULL REFERENCES merchants(id),
  currency           text NOT NULL DEFAULT 'USD',
  amount             numeric(12,2) NOT NULL CHECK (amount > 0),
  item_count         integer NOT NULL DEFAULT 0,
  -- 'manual_transfer' today; 'aba_payway_payout' once ABA enables Split & Payout
  method             text NOT NULL DEFAULT 'manual_transfer'
                       CHECK (method IN ('manual_transfer', 'aba_payway_payout')),
  status             text NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending', 'processing', 'paid', 'failed', 'cancelled')),
  -- Destination snapshot: what the money was actually sent to
  aba_account        text,
  aba_account_name   text,
  -- Bank / PayWay reference proving the transfer
  reference          text,
  note               text,
  failure_reason     text,
  created_by         text,
  completed_by       text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  paid_at            timestamptz,
  failed_at          timestamptz
);

CREATE INDEX IF NOT EXISTS idx_merchant_payouts_merchant ON merchant_payouts (merchant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_merchant_payouts_status ON merchant_payouts (status);

-- ── 4. Earnings ledger (what each order earns the merchant) ─────

CREATE TABLE IF NOT EXISTS merchant_earnings (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  merchant_id        bigint NOT NULL REFERENCES merchants(id),
  order_id           bigint REFERENCES orders(id),
  -- 'order' = sale; 'adjustment' = correction (e.g. refund after payout, negative)
  entry_type         text NOT NULL DEFAULT 'order' CHECK (entry_type IN ('order', 'adjustment')),
  currency           text NOT NULL DEFAULT 'USD',
  gross_amount       numeric(12,2) NOT NULL,   -- what the customer paid for this order
  commission_base    numeric(12,2) NOT NULL,   -- part of gross commission applies to
  commission_rate    numeric(5,2)  NOT NULL,   -- percent
  commission_amount  numeric(12,2) NOT NULL,   -- platform revenue
  net_amount         numeric(12,2) NOT NULL,   -- owed to merchant (gross - commission)
  -- 'platform' = platform received the money; 'merchant' = merchant did (e.g. COD)
  collected_by       text NOT NULL DEFAULT 'platform' CHECK (collected_by IN ('platform', 'merchant')),
  -- 'manual' = settled by merchant_payouts; 'aba_split' = ABA pays at payment time
  settlement_method  text NOT NULL DEFAULT 'manual' CHECK (settlement_method IN ('manual', 'aba_split')),
  status             text NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending', 'ready', 'paid', 'failed', 'reversed')),
  payway_tran_id     text,
  -- Payout currently carrying this earning (NULL when not in a payout)
  payout_id          bigint REFERENCES merchant_payouts(id),
  description        text,
  ready_at           timestamptz,
  paid_at            timestamptz,
  reversed_at        timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT merchant_earnings_amounts_chk
    CHECK (net_amount = gross_amount - commission_amount)
);

-- At most one sale entry per order — makes earning creation idempotent
CREATE UNIQUE INDEX IF NOT EXISTS uq_merchant_earnings_order
  ON merchant_earnings (order_id) WHERE entry_type = 'order';
CREATE INDEX IF NOT EXISTS idx_merchant_earnings_merchant_status
  ON merchant_earnings (merchant_id, status);
CREATE INDEX IF NOT EXISTS idx_merchant_earnings_payout ON merchant_earnings (payout_id);

-- ── 5. Payout items (permanent record of what each payout covered) ─

CREATE TABLE IF NOT EXISTS merchant_payout_items (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payout_id    bigint NOT NULL REFERENCES merchant_payouts(id),
  earning_id   bigint NOT NULL REFERENCES merchant_earnings(id),
  amount       numeric(12,2) NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (payout_id, earning_id)
);

-- ── 6. Audit trail (append-only) ────────────────────────────────

CREATE TABLE IF NOT EXISTS settlement_audit_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type  text NOT NULL,     -- 'merchant' | 'earning' | 'payout'
  entity_id    bigint NOT NULL,
  merchant_id  bigint,
  action       text NOT NULL,     -- e.g. 'earning.created', 'payout.paid'
  actor_type   text NOT NULL,     -- 'system' | 'super_admin' | 'merchant_admin' | 'payway'
  actor_id     text,
  old_value    jsonb,
  new_value    jsonb,
  note         text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_settlement_audit_entity ON settlement_audit_log (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_settlement_audit_merchant ON settlement_audit_log (merchant_id, created_at DESC);

CREATE OR REPLACE FUNCTION settlement_audit_log_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'settlement_audit_log is append-only';
END $$;

DROP TRIGGER IF EXISTS trg_settlement_audit_log_immutable ON settlement_audit_log;
CREATE TRIGGER trg_settlement_audit_log_immutable
  BEFORE UPDATE OR DELETE ON settlement_audit_log
  FOR EACH ROW EXECUTE FUNCTION settlement_audit_log_immutable();

-- updated_at maintenance
CREATE OR REPLACE FUNCTION settlement_touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_merchant_earnings_touch ON merchant_earnings;
CREATE TRIGGER trg_merchant_earnings_touch BEFORE UPDATE ON merchant_earnings
  FOR EACH ROW EXECUTE FUNCTION settlement_touch_updated_at();

DROP TRIGGER IF EXISTS trg_merchant_payouts_touch ON merchant_payouts;
CREATE TRIGGER trg_merchant_payouts_touch BEFORE UPDATE ON merchant_payouts
  FOR EACH ROW EXECUTE FUNCTION settlement_touch_updated_at();

-- ── 7. RLS: backend (service role) only ─────────────────────────

ALTER TABLE merchant_earnings     ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_payouts      ENABLE ROW LEVEL SECURITY;
ALTER TABLE merchant_payout_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE settlement_audit_log  ENABLE ROW LEVEL SECURITY;

-- ── 8. Balance view ─────────────────────────────────────────────
-- owed_amount           = everything earned but not yet paid out
-- available_amount      = owed and not already in an open payout
-- in_payout_amount      = in a payout awaiting transfer confirmation

CREATE OR REPLACE VIEW merchant_balances AS
SELECT
  m.id   AS merchant_id,
  m.name AS merchant_name,
  COALESCE(e.currency, 'USD') AS currency,
  COALESCE(e.pending_amount, 0)    AS pending_amount,
  COALESCE(e.available_amount, 0)  AS available_amount,
  COALESCE(e.in_payout_amount, 0)  AS in_payout_amount,
  COALESCE(e.available_amount, 0) + COALESCE(e.in_payout_amount, 0) AS owed_amount,
  COALESCE(e.paid_amount, 0)       AS paid_amount,
  COALESCE(e.failed_amount, 0)     AS failed_amount,
  COALESCE(e.gross_total, 0)       AS gross_total,
  COALESCE(e.commission_total, 0)  AS commission_total,
  e.last_earning_at
FROM merchants m
LEFT JOIN (
  SELECT
    merchant_id,
    currency,
    SUM(net_amount) FILTER (WHERE status = 'pending')                          AS pending_amount,
    SUM(net_amount) FILTER (WHERE status = 'ready' AND payout_id IS NULL
                              AND settlement_method = 'manual')                AS available_amount,
    SUM(net_amount) FILTER (WHERE status = 'ready' AND payout_id IS NOT NULL)  AS in_payout_amount,
    SUM(net_amount) FILTER (WHERE status = 'paid')                             AS paid_amount,
    SUM(net_amount) FILTER (WHERE status = 'failed')                           AS failed_amount,
    SUM(gross_amount)      FILTER (WHERE status <> 'reversed')                 AS gross_total,
    SUM(commission_amount) FILTER (WHERE status <> 'reversed')                 AS commission_total,
    MAX(created_at) AS last_earning_at
  FROM merchant_earnings
  GROUP BY merchant_id, currency
) e ON e.merchant_id = m.id;

-- ════════════════════════════════════════════════════════════════
--  Functions — every state change goes through one of these so it
--  is atomic and audited. Called by the FastAPI backend via RPC.
-- ════════════════════════════════════════════════════════════════

-- ── record_order_earning: idempotent; returns the earning row ───
CREATE OR REPLACE FUNCTION record_order_earning(
  p_order_id          bigint,
  p_merchant_id       bigint,
  p_currency          text,
  p_gross_amount      numeric,
  p_commission_base   numeric,
  p_commission_rate   numeric,
  p_commission_amount numeric,
  p_net_amount        numeric,
  p_collected_by      text,
  p_settlement_method text,
  p_payway_tran_id    text,
  p_actor_type        text,
  p_actor_id          text
) RETURNS merchant_earnings
LANGUAGE plpgsql AS $$
DECLARE
  v_row merchant_earnings;
BEGIN
  INSERT INTO merchant_earnings (
    merchant_id, order_id, entry_type, currency,
    gross_amount, commission_base, commission_rate, commission_amount, net_amount,
    collected_by, settlement_method, status, payway_tran_id
  ) VALUES (
    p_merchant_id, p_order_id, 'order', p_currency,
    p_gross_amount, p_commission_base, p_commission_rate, p_commission_amount, p_net_amount,
    p_collected_by, p_settlement_method, 'pending', p_payway_tran_id
  )
  ON CONFLICT (order_id) WHERE entry_type = 'order' DO NOTHING
  RETURNING * INTO v_row;

  IF v_row.id IS NULL THEN
    -- Already recorded (callback + poll race, retry, backfill)
    SELECT * INTO v_row FROM merchant_earnings
     WHERE order_id = p_order_id AND entry_type = 'order';
    RETURN v_row;
  END IF;

  INSERT INTO settlement_audit_log (entity_type, entity_id, merchant_id, action, actor_type, actor_id, new_value)
  VALUES ('earning', v_row.id, v_row.merchant_id, 'earning.created', p_actor_type, p_actor_id, to_jsonb(v_row));

  RETURN v_row;
END $$;

-- ── mark_order_earning_ready: order delivered → earning payable ─
CREATE OR REPLACE FUNCTION mark_order_earning_ready(
  p_order_id   bigint,
  p_actor_type text,
  p_actor_id   text
) RETURNS merchant_earnings
LANGUAGE plpgsql AS $$
DECLARE
  v_row merchant_earnings;
BEGIN
  UPDATE merchant_earnings
     SET status = 'ready', ready_at = now()
   WHERE order_id = p_order_id AND entry_type = 'order' AND status = 'pending'
  RETURNING * INTO v_row;

  IF v_row.id IS NOT NULL THEN
    INSERT INTO settlement_audit_log (entity_type, entity_id, merchant_id, action, actor_type, actor_id, old_value, new_value)
    VALUES ('earning', v_row.id, v_row.merchant_id, 'earning.ready', p_actor_type, p_actor_id,
            jsonb_build_object('status', 'pending'), jsonb_build_object('status', 'ready'));
  END IF;
  RETURN v_row;
END $$;

-- ── reverse_order_earning: order cancelled / refunded ───────────
-- Not yet paid  → earning reversed (merchant no longer owed it).
-- Already paid  → negative adjustment, deducted from the next payout.
-- In open payout → refused; fail or cancel that payout first.
CREATE OR REPLACE FUNCTION reverse_order_earning(
  p_order_id   bigint,
  p_reason     text,
  p_actor_type text,
  p_actor_id   text
) RETURNS merchant_earnings
LANGUAGE plpgsql AS $$
DECLARE
  v_row merchant_earnings;
  v_adj merchant_earnings;
BEGIN
  SELECT * INTO v_row FROM merchant_earnings
   WHERE order_id = p_order_id AND entry_type = 'order'
   FOR UPDATE;

  IF v_row.id IS NULL OR v_row.status = 'reversed' THEN
    RETURN v_row;
  END IF;

  IF v_row.payout_id IS NOT NULL AND v_row.status <> 'paid' THEN
    RAISE EXCEPTION 'Earning % is in open payout %; fail or cancel the payout first',
      v_row.id, v_row.payout_id USING ERRCODE = 'P0001';
  END IF;

  IF v_row.status = 'paid' THEN
    INSERT INTO merchant_earnings (
      merchant_id, order_id, entry_type, currency,
      gross_amount, commission_base, commission_rate, commission_amount, net_amount,
      collected_by, settlement_method, status, ready_at, description
    ) VALUES (
      v_row.merchant_id, v_row.order_id, 'adjustment', v_row.currency,
      -v_row.gross_amount, -v_row.commission_base, v_row.commission_rate,
      -v_row.commission_amount, -v_row.net_amount,
      v_row.collected_by, 'manual', 'ready', now(),
      'Reversal of paid earning #' || v_row.id || COALESCE(': ' || p_reason, '')
    ) RETURNING * INTO v_adj;

    INSERT INTO settlement_audit_log (entity_type, entity_id, merchant_id, action, actor_type, actor_id, new_value, note)
    VALUES ('earning', v_adj.id, v_adj.merchant_id, 'earning.adjustment_created', p_actor_type, p_actor_id, to_jsonb(v_adj), p_reason);
    RETURN v_adj;
  END IF;

  UPDATE merchant_earnings
     SET status = 'reversed', reversed_at = now(),
         description = COALESCE(p_reason, description)
   WHERE id = v_row.id
  RETURNING * INTO v_adj;

  INSERT INTO settlement_audit_log (entity_type, entity_id, merchant_id, action, actor_type, actor_id, old_value, new_value, note)
  VALUES ('earning', v_row.id, v_row.merchant_id, 'earning.reversed', p_actor_type, p_actor_id,
          jsonb_build_object('status', v_row.status), jsonb_build_object('status', 'reversed'), p_reason);
  RETURN v_adj;
END $$;

-- ── create_merchant_payout: bundle all available earnings ───────
CREATE OR REPLACE FUNCTION create_merchant_payout(
  p_merchant_id bigint,
  p_currency    text,
  p_method      text,
  p_note        text,
  p_actor_type  text,
  p_actor_id    text
) RETURNS merchant_payouts
LANGUAGE plpgsql AS $$
DECLARE
  v_merchant merchants;
  v_total    numeric(12,2);
  v_count    integer;
  v_payout   merchant_payouts;
BEGIN
  -- Serialise payout creation per merchant
  SELECT * INTO v_merchant FROM merchants WHERE id = p_merchant_id FOR UPDATE;
  IF v_merchant.id IS NULL THEN
    RAISE EXCEPTION 'Merchant % not found', p_merchant_id USING ERRCODE = 'P0002';
  END IF;

  PERFORM 1 FROM merchant_earnings
   WHERE merchant_id = p_merchant_id AND currency = p_currency
     AND status = 'ready' AND payout_id IS NULL AND settlement_method = 'manual'
   FOR UPDATE;

  SELECT COALESCE(SUM(net_amount), 0), COUNT(*) INTO v_total, v_count
    FROM merchant_earnings
   WHERE merchant_id = p_merchant_id AND currency = p_currency
     AND status = 'ready' AND payout_id IS NULL AND settlement_method = 'manual';

  IF v_count = 0 OR v_total <= 0 THEN
    RAISE EXCEPTION 'Nothing to pay out for merchant % (available %)', p_merchant_id, v_total
      USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO merchant_payouts (
    merchant_id, currency, amount, item_count, method, status,
    aba_account, aba_account_name, note, created_by
  ) VALUES (
    p_merchant_id, p_currency, v_total, v_count, p_method, 'pending',
    v_merchant.aba_account, v_merchant.aba_account_name, p_note, p_actor_id
  ) RETURNING * INTO v_payout;

  INSERT INTO merchant_payout_items (payout_id, earning_id, amount)
  SELECT v_payout.id, id, net_amount FROM merchant_earnings
   WHERE merchant_id = p_merchant_id AND currency = p_currency
     AND status = 'ready' AND payout_id IS NULL AND settlement_method = 'manual';

  UPDATE merchant_earnings SET payout_id = v_payout.id
   WHERE id IN (SELECT earning_id FROM merchant_payout_items WHERE payout_id = v_payout.id);

  INSERT INTO settlement_audit_log (entity_type, entity_id, merchant_id, action, actor_type, actor_id, new_value, note)
  VALUES ('payout', v_payout.id, p_merchant_id, 'payout.created', p_actor_type, p_actor_id, to_jsonb(v_payout), p_note);

  RETURN v_payout;
END $$;

-- ── complete_merchant_payout: transfer confirmed ────────────────
CREATE OR REPLACE FUNCTION complete_merchant_payout(
  p_payout_id  bigint,
  p_reference  text,
  p_actor_type text,
  p_actor_id   text
) RETURNS merchant_payouts
LANGUAGE plpgsql AS $$
DECLARE
  v_payout merchant_payouts;
BEGIN
  SELECT * INTO v_payout FROM merchant_payouts WHERE id = p_payout_id FOR UPDATE;
  IF v_payout.id IS NULL THEN
    RAISE EXCEPTION 'Payout % not found', p_payout_id USING ERRCODE = 'P0002';
  END IF;
  IF v_payout.status NOT IN ('pending', 'processing') THEN
    RAISE EXCEPTION 'Payout % is %, cannot mark paid', p_payout_id, v_payout.status USING ERRCODE = 'P0001';
  END IF;
  IF COALESCE(trim(p_reference), '') = '' THEN
    RAISE EXCEPTION 'A transfer reference is required' USING ERRCODE = 'P0001';
  END IF;

  UPDATE merchant_payouts
     SET status = 'paid', reference = p_reference, paid_at = now(), completed_by = p_actor_id
   WHERE id = p_payout_id
  RETURNING * INTO v_payout;

  UPDATE merchant_earnings SET status = 'paid', paid_at = now()
   WHERE payout_id = p_payout_id;

  INSERT INTO settlement_audit_log (entity_type, entity_id, merchant_id, action, actor_type, actor_id, new_value)
  VALUES ('payout', v_payout.id, v_payout.merchant_id, 'payout.paid', p_actor_type, p_actor_id,
          jsonb_build_object('status', 'paid', 'reference', p_reference, 'amount', v_payout.amount));
  RETURN v_payout;
END $$;

-- ── fail_merchant_payout: transfer failed / cancelled ───────────
-- Earnings are released back to 'ready' so they can be paid again;
-- merchant_payout_items keeps the history.
CREATE OR REPLACE FUNCTION fail_merchant_payout(
  p_payout_id  bigint,
  p_reason     text,
  p_cancel     boolean,
  p_actor_type text,
  p_actor_id   text
) RETURNS merchant_payouts
LANGUAGE plpgsql AS $$
DECLARE
  v_payout merchant_payouts;
  v_status text := CASE WHEN p_cancel THEN 'cancelled' ELSE 'failed' END;
BEGIN
  SELECT * INTO v_payout FROM merchant_payouts WHERE id = p_payout_id FOR UPDATE;
  IF v_payout.id IS NULL THEN
    RAISE EXCEPTION 'Payout % not found', p_payout_id USING ERRCODE = 'P0002';
  END IF;
  IF v_payout.status NOT IN ('pending', 'processing') THEN
    RAISE EXCEPTION 'Payout % is %, cannot mark %', p_payout_id, v_payout.status, v_status USING ERRCODE = 'P0001';
  END IF;

  UPDATE merchant_payouts
     SET status = v_status, failure_reason = p_reason, failed_at = now(), completed_by = p_actor_id
   WHERE id = p_payout_id
  RETURNING * INTO v_payout;

  UPDATE merchant_earnings SET payout_id = NULL
   WHERE payout_id = p_payout_id;

  INSERT INTO settlement_audit_log (entity_type, entity_id, merchant_id, action, actor_type, actor_id, new_value, note)
  VALUES ('payout', v_payout.id, v_payout.merchant_id, 'payout.' || v_status, p_actor_type, p_actor_id,
          jsonb_build_object('status', v_status), p_reason);
  RETURN v_payout;
END $$;

-- Functions are for the backend only
REVOKE ALL ON FUNCTION record_order_earning(bigint,bigint,text,numeric,numeric,numeric,numeric,numeric,text,text,text,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION mark_order_earning_ready(bigint,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION reverse_order_earning(bigint,text,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION create_merchant_payout(bigint,text,text,text,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION complete_merchant_payout(bigint,text,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION fail_merchant_payout(bigint,text,boolean,text,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON merchant_balances FROM anon, authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';
